import linear_equations_linear_algebraic_aspects_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace linear_equations_linear_algebraic_aspects_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end linear_equations_linear_algebraic_aspects_theorem_canonical_lane_mathlib
end HautevilleHouse
